// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWorld.proto

package com.vichen.hello.proto;

public final class HelloWorld {
  private HelloWorld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 枚举类型，必须从0开始，序号可跨越。同一包下不能重名，所以加前缀来区别
   * </pre>
   *
   * Protobuf enum {@code com.vichen.hello.proto.Tt}
   */
  public enum Tt
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>T1 = 0;</code>
     */
    T1(0),
    /**
     * <code>T2 = 1;</code>
     */
    T2(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>T1 = 0;</code>
     */
    public static final int T1_VALUE = 0;
    /**
     * <code>T2 = 1;</code>
     */
    public static final int T2_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Tt valueOf(int value) {
      return forNumber(value);
    }

    public static Tt forNumber(int value) {
      switch (value) {
        case 0: return T1;
        case 1: return T2;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Tt>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Tt> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Tt>() {
            public Tt findValueByNumber(int number) {
              return Tt.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.vichen.hello.proto.HelloWorld.getDescriptor().getEnumTypes().get(0);
    }

    private static final Tt[] VALUES = values();

    public static Tt valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Tt(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.vichen.hello.proto.Tt)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.vichen.hello.proto.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   *required：值不可为空
   *optional：可选字段
   *singular：符合语法规则的消息包含零个或者一个这样的字段（最多一个）
   *repeated：一个字段在合法的消息中可以重复出现一定次数（包括零次）。重复出现的值的次序将被保留。在proto3中，重复出现的值类型字段默认采用压缩编码。你可以在这里找到更多关于压缩编码的东西： Protocol Buffer Encoding。
   *默认值： optional PhoneType type = 2 [default = HOME];
   *proto3中，省略required,optional,singular，由protoc自动选择。
   * </pre>
   *
   * Protobuf type {@code com.vichen.hello.proto.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.vichen.hello.proto.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vichen.hello.proto.HelloWorld.Request.class, com.vichen.hello.proto.HelloWorld.Request.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vichen.hello.proto.HelloWorld.Request)) {
        return super.equals(obj);
      }
      com.vichen.hello.proto.HelloWorld.Request other = (com.vichen.hello.proto.HelloWorld.Request) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vichen.hello.proto.HelloWorld.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vichen.hello.proto.HelloWorld.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vichen.hello.proto.HelloWorld.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *required：值不可为空
     *optional：可选字段
     *singular：符合语法规则的消息包含零个或者一个这样的字段（最多一个）
     *repeated：一个字段在合法的消息中可以重复出现一定次数（包括零次）。重复出现的值的次序将被保留。在proto3中，重复出现的值类型字段默认采用压缩编码。你可以在这里找到更多关于压缩编码的东西： Protocol Buffer Encoding。
     *默认值： optional PhoneType type = 2 [default = HOME];
     *proto3中，省略required,optional,singular，由protoc自动选择。
     * </pre>
     *
     * Protobuf type {@code com.vichen.hello.proto.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.vichen.hello.proto.Request)
        com.vichen.hello.proto.HelloWorld.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vichen.hello.proto.HelloWorld.Request.class, com.vichen.hello.proto.HelloWorld.Request.Builder.class);
      }

      // Construct using com.vichen.hello.proto.HelloWorld.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Request_descriptor;
      }

      public com.vichen.hello.proto.HelloWorld.Request getDefaultInstanceForType() {
        return com.vichen.hello.proto.HelloWorld.Request.getDefaultInstance();
      }

      public com.vichen.hello.proto.HelloWorld.Request build() {
        com.vichen.hello.proto.HelloWorld.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.vichen.hello.proto.HelloWorld.Request buildPartial() {
        com.vichen.hello.proto.HelloWorld.Request result = new com.vichen.hello.proto.HelloWorld.Request(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vichen.hello.proto.HelloWorld.Request) {
          return mergeFrom((com.vichen.hello.proto.HelloWorld.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vichen.hello.proto.HelloWorld.Request other) {
        if (other == com.vichen.hello.proto.HelloWorld.Request.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vichen.hello.proto.HelloWorld.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vichen.hello.proto.HelloWorld.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.vichen.hello.proto.Request)
    }

    // @@protoc_insertion_point(class_scope:com.vichen.hello.proto.Request)
    private static final com.vichen.hello.proto.HelloWorld.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vichen.hello.proto.HelloWorld.Request();
    }

    public static com.vichen.hello.proto.HelloWorld.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.vichen.hello.proto.HelloWorld.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.vichen.hello.proto.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string data = 1;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */
    int getProjectsCount();
    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */
    boolean containsProjects(
        java.lang.String key);
    /**
     * Use {@link #getProjectsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getProjects();
    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getProjectsMap();
    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */

    java.lang.String getProjectsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */

    java.lang.String getProjectsOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   *声明类
   * </pre>
   *
   * Protobuf type {@code com.vichen.hello.proto.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.vichen.hello.proto.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                projects_ = com.google.protobuf.MapField.newMapField(
                    ProjectsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              projects__ = input.readMessage(
                  ProjectsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              projects_.getMutableMap().put(
                  projects__.getKey(), projects__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Response_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetProjects();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vichen.hello.proto.HelloWorld.Response.class, com.vichen.hello.proto.HelloWorld.Response.Builder.class);
    }

    private int bitField0_;
    public static final int DATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 1;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTS_FIELD_NUMBER = 3;
    private static final class ProjectsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Response_ProjectsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> projects_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProjects() {
      if (projects_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ProjectsDefaultEntryHolder.defaultEntry);
      }
      return projects_;
    }

    public int getProjectsCount() {
      return internalGetProjects().getMap().size();
    }
    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */

    public boolean containsProjects(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetProjects().getMap().containsKey(key);
    }
    /**
     * Use {@link #getProjectsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProjects() {
      return getProjectsMap();
    }
    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getProjectsMap() {
      return internalGetProjects().getMap();
    }
    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */

    public java.lang.String getProjectsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProjects().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *map 类型
     * </pre>
     *
     * <code>map&lt;string, string&gt; projects = 3;</code>
     */

    public java.lang.String getProjectsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProjects().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetProjects(),
          ProjectsDefaultEntryHolder.defaultEntry,
          3);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProjects().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        projects__ = ProjectsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, projects__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vichen.hello.proto.HelloWorld.Response)) {
        return super.equals(obj);
      }
      com.vichen.hello.proto.HelloWorld.Response other = (com.vichen.hello.proto.HelloWorld.Response) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && internalGetProjects().equals(
          other.internalGetProjects());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      if (!internalGetProjects().getMap().isEmpty()) {
        hash = (37 * hash) + PROJECTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetProjects().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vichen.hello.proto.HelloWorld.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vichen.hello.proto.HelloWorld.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vichen.hello.proto.HelloWorld.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *声明类
     * </pre>
     *
     * Protobuf type {@code com.vichen.hello.proto.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.vichen.hello.proto.Response)
        com.vichen.hello.proto.HelloWorld.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Response_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetProjects();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableProjects();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vichen.hello.proto.HelloWorld.Response.class, com.vichen.hello.proto.HelloWorld.Response.Builder.class);
      }

      // Construct using com.vichen.hello.proto.HelloWorld.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = "";

        internalGetMutableProjects().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vichen.hello.proto.HelloWorld.internal_static_com_vichen_hello_proto_Response_descriptor;
      }

      public com.vichen.hello.proto.HelloWorld.Response getDefaultInstanceForType() {
        return com.vichen.hello.proto.HelloWorld.Response.getDefaultInstance();
      }

      public com.vichen.hello.proto.HelloWorld.Response build() {
        com.vichen.hello.proto.HelloWorld.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.vichen.hello.proto.HelloWorld.Response buildPartial() {
        com.vichen.hello.proto.HelloWorld.Response result = new com.vichen.hello.proto.HelloWorld.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.data_ = data_;
        result.projects_ = internalGetProjects();
        result.projects_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vichen.hello.proto.HelloWorld.Response) {
          return mergeFrom((com.vichen.hello.proto.HelloWorld.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vichen.hello.proto.HelloWorld.Response other) {
        if (other == com.vichen.hello.proto.HelloWorld.Response.getDefaultInstance()) return this;
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        internalGetMutableProjects().mergeFrom(
            other.internalGetProjects());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vichen.hello.proto.HelloWorld.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vichen.hello.proto.HelloWorld.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 1;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 1;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 1;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> projects_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetProjects() {
        if (projects_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ProjectsDefaultEntryHolder.defaultEntry);
        }
        return projects_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableProjects() {
        onChanged();;
        if (projects_ == null) {
          projects_ = com.google.protobuf.MapField.newMapField(
              ProjectsDefaultEntryHolder.defaultEntry);
        }
        if (!projects_.isMutable()) {
          projects_ = projects_.copy();
        }
        return projects_;
      }

      public int getProjectsCount() {
        return internalGetProjects().getMap().size();
      }
      /**
       * <pre>
       *map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; projects = 3;</code>
       */

      public boolean containsProjects(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetProjects().getMap().containsKey(key);
      }
      /**
       * Use {@link #getProjectsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getProjects() {
        return getProjectsMap();
      }
      /**
       * <pre>
       *map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; projects = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getProjectsMap() {
        return internalGetProjects().getMap();
      }
      /**
       * <pre>
       *map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; projects = 3;</code>
       */

      public java.lang.String getProjectsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetProjects().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; projects = 3;</code>
       */

      public java.lang.String getProjectsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetProjects().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearProjects() {
        internalGetMutableProjects().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; projects = 3;</code>
       */

      public Builder removeProjects(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableProjects().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableProjects() {
        return internalGetMutableProjects().getMutableMap();
      }
      /**
       * <pre>
       *map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; projects = 3;</code>
       */
      public Builder putProjects(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableProjects().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *map 类型
       * </pre>
       *
       * <code>map&lt;string, string&gt; projects = 3;</code>
       */

      public Builder putAllProjects(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableProjects().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.vichen.hello.proto.Response)
    }

    // @@protoc_insertion_point(class_scope:com.vichen.hello.proto.Response)
    private static final com.vichen.hello.proto.HelloWorld.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vichen.hello.proto.HelloWorld.Response();
    }

    public static com.vichen.hello.proto.HelloWorld.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.vichen.hello.proto.HelloWorld.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vichen_hello_proto_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vichen_hello_proto_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vichen_hello_proto_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vichen_hello_proto_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vichen_hello_proto_Response_ProjectsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_vichen_hello_proto_Response_ProjectsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloWorld.proto\022\026com.vichen.hello.pro" +
      "to\"\027\n\007Request\022\014\n\004name\030\001 \001(\t\"\213\001\n\010Response" +
      "\022\014\n\004data\030\001 \001(\t\022@\n\010projects\030\003 \003(\0132..com.v" +
      "ichen.hello.proto.Response.ProjectsEntry" +
      "\032/\n\rProjectsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001*\024\n\002Tt\022\006\n\002T1\020\000\022\006\n\002T2\020\0012\373\002\n\021Hell" +
      "oWorldService\022O\n\010sayHello\022\037.com.vichen.h" +
      "ello.proto.Request\032 .com.vichen.hello.pr" +
      "oto.Response\"\000\022_\n\026sayHelloStreamResponse" +
      "\022\037.com.vichen.hello.proto.Request\032 .com.",
      "vichen.hello.proto.Response\"\0000\001\022^\n\025sayHe" +
      "lloStreamRequest\022\037.com.vichen.hello.prot" +
      "o.Request\032 .com.vichen.hello.proto.Respo" +
      "nse\"\000(\001\022T\n\tchatHello\022\037.com.vichen.hello." +
      "proto.Request\032 .com.vichen.hello.proto.R" +
      "esponse\"\000(\0010\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_vichen_hello_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vichen_hello_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vichen_hello_proto_Request_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_vichen_hello_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_vichen_hello_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vichen_hello_proto_Response_descriptor,
        new java.lang.String[] { "Data", "Projects", });
    internal_static_com_vichen_hello_proto_Response_ProjectsEntry_descriptor =
      internal_static_com_vichen_hello_proto_Response_descriptor.getNestedTypes().get(0);
    internal_static_com_vichen_hello_proto_Response_ProjectsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_vichen_hello_proto_Response_ProjectsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
